on:
  push:
    branches:
    - main
  pull_request:
name: Tests
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.23.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test
      run: |
        go version
        go test -race ./...
